"""Reliability Diagnostics: the L1 shadow-observer contract."""

from .envelope import (
    CAPABILITY_ID,
    CONTROL_FIELD_FAMILIES,
    DSH_PROVIDER_ID,
    ENVELOPE_FIELDS,
    OBSERVER_ENVELOPE_SCHEMA_VERSION,
    OBSERVER_STATS_SCHEMA_VERSION,
    RAW_MATERIAL_FIELD_FAMILIES,
    SOURCE_REF_FIELDS,
    SUMMARY_FIELDS,
    ClockSource,
    EnvelopeRejection,
    ObserverEnvelope,
    ObserverEnvelopeError,
    ObserverEventKind,
    normalize_observer_envelope,
)
from .fixture import FIXTURE_GOAL_ID, dsh_fixture_records, run_dsh_fixture
from .intake import (
    DEFAULT_BUFFER_BOUND,
    RUN_IDENTITY_FIELDS,
    ObserverRunIdentity,
    ObserverStats,
    ShadowObserverIntake,
    normalize_observer_run_identity,
    normalize_observer_stats,
)
from .ledger import (
    LEDGER_DIRNAME,
    append_ledger_records,
    ledger_path,
    ledger_ref,
    parse_ndjson_lines,
    read_ledger_records,
)
from .projection import (
    DIAGNOSTIC_PROJECTION_SCHEMA_VERSION,
    DiagnosticSignal,
    DiagnosticStage,
    build_diagnostic_projection,
)
from .receipt import (
    INTEGRITY_RECEIPT_SCHEMA_VERSION,
    LedgerReading,
    ReceiptReason,
    ReceiptStatus,
    build_integrity_receipt,
    read_ledger,
)

__all__ = [
    "CAPABILITY_ID",
    "CONTROL_FIELD_FAMILIES",
    "DEFAULT_BUFFER_BOUND",
    "DIAGNOSTIC_PROJECTION_SCHEMA_VERSION",
    "DSH_PROVIDER_ID",
    "ENVELOPE_FIELDS",
    "FIXTURE_GOAL_ID",
    "INTEGRITY_RECEIPT_SCHEMA_VERSION",
    "LEDGER_DIRNAME",
    "OBSERVER_ENVELOPE_SCHEMA_VERSION",
    "OBSERVER_STATS_SCHEMA_VERSION",
    "RAW_MATERIAL_FIELD_FAMILIES",
    "RUN_IDENTITY_FIELDS",
    "SOURCE_REF_FIELDS",
    "SUMMARY_FIELDS",
    "ClockSource",
    "DiagnosticSignal",
    "DiagnosticStage",
    "EnvelopeRejection",
    "LedgerReading",
    "ObserverEnvelope",
    "ObserverEnvelopeError",
    "ObserverEventKind",
    "ObserverRunIdentity",
    "ObserverStats",
    "ReceiptReason",
    "ReceiptStatus",
    "ShadowObserverIntake",
    "append_ledger_records",
    "build_diagnostic_projection",
    "build_integrity_receipt",
    "dsh_fixture_records",
    "ledger_path",
    "ledger_ref",
    "normalize_observer_envelope",
    "normalize_observer_run_identity",
    "normalize_observer_stats",
    "parse_ndjson_lines",
    "read_ledger",
    "read_ledger_records",
    "run_dsh_fixture",
]
