import type { ReviewExportLabels } from "../../data/delivery-review.js";

const en = {
  title: "Delivery & evidence", scope: "Current work and a limited set of predecessors. Use Tasks for the full task inventory.",
  observed: "Snapshot read", chain: "Delivery chain", relations: "Relationships", acceptance: "Acceptance observations",
  acceptanceBoundary: "Completed tasks and recorded evidence do not certify Goal acceptance.",
  noGraph: "No delivery chain is available in this snapshot. This does not mean all work is complete.",
  incomplete: "Some related information is missing or not expanded.",
  unavailable: "Unknown", refs: "Source references", required: "Evidence still required", guards: "Pending decisions", next: "Next action",
  owner: "Owner", reason: "Reason", historical: "Historical observations", checks: "Component checks", missingSources: "Missing sources", observedScope: "Observation coverage",
  kind: { deliverable: "Work", gate: "Decision", gate_summary: "Other decisions", lease: "Ownership", validation: "Validation", repair: "Recovery", handoff: "Handoff", evidence: "Evidence" },
  state: { open: "Open", ready: "Ready", blocked: "Blocked", done: "Done", waiting: "Waiting", unknown: "Unknown" },
  relation: { depends_on: "depends on", blocks: "blocks", validates: "validates / contextualizes", repairs: "repairs", audits: "audits", continues: "continues", hands_off_to: "hands off to", supersedes: "supersedes" },
  refresh: "Refresh snapshot", export: "Export delivery snapshot", exported: "Snapshot downloaded", loading: "Reading the current delivery chain…",
  error: "The delivery snapshot could not be read. Refresh to retry.",
  refreshError: "Refresh failed. The previous snapshot remains visible; refresh before opening linked work or exporting.",
  changed: "Workspace facts changed after this snapshot. Refresh before opening linked work or exporting.",
  search: "Search title, owner or reference", all: "All nodes", conditions: "Conditions & owners", evidence: "Evidence & handoffs", related: "Directly related",
  map: "Map", list: "List", view: "Delivery chain layout", filter: "Delivery chain focus", visible: "Visible", empty: "No nodes match these filters.",
  reset: "Reset filters", select: "Select a node to trace its relationships and open its source.",
  work: "Work", context: "Evidence & recovery", details: "Selected item", noRelations: "No relationships are recorded for this item.",
  openTask: "Open task", openGate: "Review decision", openRun: "Open execution",
  sourceUnavailable: "The linked item is not in the current workspace. Use its reference in the task board or CLI.",
  omittedGates: "Decisions not expanded", missing: "Missing predecessors", clipped: "Expansion limited", sourceClipped: "Source truncated", yes: "Yes", no: "No", chainOnly: "Bounded chain", exportFailed: "Download failed. Please retry.",
} satisfies ReviewExportLabels & Record<string, unknown>;

const zh: typeof en = {
  title: "交付与依据", scope: "仅含当前工作及有限前序，完整任务清单见任务页。",
  observed: "快照读取时间", chain: "交付链", relations: "关联关系", acceptance: "验收观察",
  acceptanceBoundary: "任务完成、已有证据均不等于 Goal 已通过验收。",
  noGraph: "当前快照没有可展示的交付链，这不代表工作已经全部完成。",
  incomplete: "部分关联信息缺失或未展开。",
  unavailable: "未知", refs: "来源引用", required: "仍需补齐的证据", guards: "待你处理", next: "下一步",
  owner: "负责人", reason: "原因", historical: "历史观察", checks: "组成检查", missingSources: "缺失来源", observedScope: "观察范围",
  kind: { deliverable: "工作", gate: "决策", gate_summary: "其他决策", lease: "责任归属", validation: "验证", repair: "恢复", handoff: "交接", evidence: "证据" },
  state: { open: "待处理", ready: "就绪", blocked: "受阻", done: "已完成", waiting: "等待", unknown: "未知" },
  relation: { depends_on: "依赖", blocks: "阻塞", validates: "验证 / 提供背景", repairs: "修复", audits: "复核", continues: "延续", hands_off_to: "交接给", supersedes: "替代" },
  refresh: "刷新快照", export: "导出交付快照", exported: "快照已下载", loading: "正在读取当前交付链…",
  error: "交付快照读取失败，请刷新重试。",
  refreshError: "刷新失败，当前保留上次快照；请刷新后再打开关联工作或导出。",
  changed: "工作区状态已在此快照之后变化，请刷新后再打开关联工作或导出。",
  search: "搜索标题、负责人或引用", all: "全部节点", conditions: "条件与责任", evidence: "证据与交接", related: "直接关联",
  map: "关系图", list: "列表", view: "交付链布局", filter: "交付链范围", visible: "当前显示", empty: "没有匹配当前筛选的节点。",
  reset: "重置筛选", select: "选择一个节点，追溯关联关系并打开来源。",
  work: "工作", context: "证据与恢复", details: "选中事项", noRelations: "当前快照未记录此事项的关联关系。",
  openTask: "打开任务", openGate: "查看决策", openRun: "打开执行",
  sourceUnavailable: "关联事项未出现在当前工作区，可使用其引用到任务看板或 CLI 查找。",
  omittedGates: "未展开决策", missing: "缺失前序", clipped: "展开受限", sourceClipped: "来源被裁剪", yes: "是", no: "否", chainOnly: "当前局部链", exportFailed: "下载失败，请重试。",
};
export const deliveryReviewCopy = { en, "zh-CN": zh };
