// Generated by scripts/generate_semantic_bindings.py; do not edit.
// Value owner: loopx/control_plane/agents/agent_scope_frontier.py::AgentScopeFrontierAction

export const AGENT_SCOPE_FRONTIER_ACTIONS = [
  "agent_scope_exhausted",
  "agent_scope_wait",
  "reassignment_required",
  "successor_replan_required",
] as const;
export type AgentScopeFrontierActionValue = (typeof AGENT_SCOPE_FRONTIER_ACTIONS)[number];

export const AgentScopeFrontierAction = {
  AGENT_SCOPE_EXHAUSTED: AGENT_SCOPE_FRONTIER_ACTIONS[0],
  AGENT_SCOPE_WAIT: AGENT_SCOPE_FRONTIER_ACTIONS[1],
  REASSIGNMENT_REQUIRED: AGENT_SCOPE_FRONTIER_ACTIONS[2],
  SUCCESSOR_REPLAN_REQUIRED: AGENT_SCOPE_FRONTIER_ACTIONS[3],
} as const;
